server:
  port: 8888

spring:
#  profiles:
#    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/williamsilvaec/microservice-repo
          search-paths: fornecedor
